# MAG
# https://github.com/diydrones/ardupilot/blob/master/libraries/DataFlash/DataFlash.h#L461
Header header
int16 MagX   # int16_t  mag_x;
int16 MagY   # int16_t  mag_y;
int16 MagZ   # int16_t  mag_z;
int16 OfsX   # int16_t  offset_x;
int16 OfsY   # int16_t  offset_y;
int16 OfsZ   # int16_t  offset_z;
int16 MOfsX  # int16_t  motor_offset_x;
int16 MOfsY  # int16_t  motor_offset_y;
int16 MOfsZ  # int16_t  motor_offset_z;
			 # uint8_t  health; TODO: